### ISSUE TITLE
Greengrass deployment rostopic list not same as EC2 rostopic list

### ISSUE THREAD

**Issue by josephjoel3099** [aws-greengrass/aws-greengrass-cli#138]
The rostopics after launching a launch file in the EC2 instance shows a aset of topics which the robot needs to run properly. After deploying the same stack on a RPi 4 (4 GB) using greengrass the list of rostopics reduces and while echoing the rostopic it give a warning saying "Is /clock being published."

The expected behaviour is to see the same rostopic list as listed in the EC2 instance after the greengrass deployment with the same launch file.

To add, we also checked the rosnode list for the same and it to had some of the node omitted from the actual list while deploying.

 - OS: Ubuntu 18.04
 - Greengrass ver: 1.0
 - ROS: Melodic

Due to the bug we are not able to launch rviz properly and see the topics on the romote machine running the same config.

Note: We are running Rasbian OS on the RPi where the bundle is deployed. Build and bundle is done on the EC2 instance running Ubuntu 18.04, ROS Melodic installed, ARM64.

**Comment by MikeDombo** [comment]
Hello Joseph,
Have you contacted the ROS team about this issue? I am not clear on what the problem is and how it relates to Greengrass.

You note that the Greengrass version is Greengrass version 1, version 1 is not open source and our GitHub repositories do not apply to that software.

Please reach out to AWS support or the AWS forums for help in this matter.
