### ISSUE TITLE
(GreenGrassRuntime): Using Graalvm based native binaries to remove java dependency on the core devices

### ISSUE THREAD

**Issue by rverma-nsl** [aws-greengrass/aws-greengrass-cli#150]
**Feature Description**
Currently greegrass runtime requires java pre installed. Apart from increasing installation complexity, it also required more memory for runtime and sometimes limiting when we need to implement core devices with higher no of devices.

**Use Case**
Easier management.

**Proposed Solution**
Generate multiple platform binaries using graal. Will need to use different architecture based machines in the CI to generate them.

**Other**
Solutions like Kube-edge exists which abstracts similar complexity using the native binaries itself.

* [x] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hello Rohit,
Thank you very much for your suggestion. We have actually tried statically compiling Greengrass using GraalVM Native Image, however we did not achieve good results. The size on disk was roughly 500MB and the runtime memory usage was around 350-400MB. So based on those results, using a standard JVM was actually significantly smaller and therefore we have given up on Graal Native Image for now. 
Even if the memory usage was better, Graal does not support dynamically loading jars into the VM, so it would mean that no plugins to Greengrass could be used.
Since Greengrass is open source, you are most welcome to use the source and build it using Graal or anything else that you wish, however, given our previous results I do not think that you'd be very happy with the result.
